name: New Project Issue
description: Create A New Project Issue Using This Form
title: "[BUG] <Descriptive Title>"
labels: [Bug, Needs Triage, Product Backlog]
body:
- type: input
  id: related-issue
  attributes:
    label: Tag Related Issues, Pull Requests and Discussions
    description: "Please tag related repository content using it hashtag"
    placeholder: "#2021 #2020"
  validations:
    required: false
- type: input
  id: related-user-story
  attributes:
    label: Tag Related User Storie(s)
    placeholder: "#2021 #2020"
  validations:
    required: false
- type: dropdown
  id: issue-check
  attributes:
    label: Is there an existing issue for this?
    description: Before Creating New Issues, Please Ensure There Is No Other Issue This Will Duplicate.
    options:
      - Yes, I have checked. There Is No Other Issue Open
      - No, I have not checked but I Will
  validations:
    required: true
- type: dropdown
  id: client-knows
  attributes:
    label: Is the Client Aware Of This Issue?
    description: Should the client be consulted?
    options:
      - Yes, They Know.
      - No, But They Should Be Consulted
      - No, This Is Not Client Related
      - Not Sure
  validations:
    required: true
- type: dropdown
  id: section
  attributes:
    label: Which Section Of The Application Does This Error Occur?
    options:
      - Administration/Super User
      - Lecturer 
      - Dashboard
      - Student
      - Cohort
      - Notes
      - Evidence Uploads
      - Studio Paper
      - Authentication
      - Test Deployment
      - Production Deployment
      - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue Details
    description: A concise description of the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: Describe how this should function.
  validations:
    required: true
- type: textarea
  attributes:
    label: Add Screenshots Of The Error/Issue
    description: Copy And Paste Image(s) Into The Text Area Below
  validations:
    required: false
- type: textarea
  id: solutions
  attributes:
    label: Steps To Resolve This Issue
    description: |
      #### Please Provide A Check List Of Steps Needed To Resolve This.
      *Include any research, testing that might be needed*
  validations:
    required: true
- type: dropdown
  id: complexity
  attributes:
    label: How Difficult Will This Task Be To Complete In A Single Sprint?
    description:
      Level 1 = no research or testing required, less than 30 minutes work
      Level 2 = no research or testing less than 2 hours work, no more than 10 commits
      Level 3 = research required, 2-5 hours work
      Level 4 = research, additional testing 5 - 8 hours
      Level 5 = research, additional testing, redevelopment 8-10 Hours Work Possible
    options:
      - Level 5 - 8-10+ Hours 
      - Level 4 - 5-8 Hours
      - Level 3 - 2-5 Hours
      - Level 2 - <2 Hours
      - Level 1 - <30 Minutes
  validations:
    required: true
- type: dropdown
  id: assign-to
  attributes:
    label: Which Team Member Should Look Into This Issue?
    multiple: true
    options:
      - Sam
      - Anthony
      - Matt
      - Mitchell
      - Not Sure
  validations:
    required: true
- type: checkboxes
  id: requires
  attributes:
    label: This Issue Will Likely Require.....
    description: This issue may need more frequent input from stakeholders, team members
    options:
      - label: Client Consultation
      - label: Team Testing and Feedback
      - label: Researching Possible Solutions
      - label: Testing In Local Environment
      - label: New Dusk Tests Developed
      - label: Current Dusk Tests Amended
- type: textarea
  attributes:
    label: Anything Else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false