name: Auto Assign Author

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened]

jobs:
  Auto-Assign-Author:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/auto_assign_author.yml
