name: Create Pending Status On PR

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  set-pr-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Status To Pending
        uses: niteoweb/pull_request_status_action@v1.0.0
        with:
          pr_number: ${{ github.event.pull_request.number }}
          state: pending
          context: review-app-test
          repository: ${{ github.repository }}
          description: Waiting for Review App to Deploy Successfully
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}