name: Delete old workflow runs
on:
  schedule:
    - cron:  '0 8 * * 0-6'
    - cron:  '0 21 * * 0-6'
jobs:
  delete_workflow_run:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 15