name: Pull Request Reminder-Teams Channel
on:
  schedule:
    - cron: "0 20 * * 1-5"
    # Weekdays 9am NZST
    - cron: "0 3 * * 1-5"
    # Weekdays 4pm NZST
jobs:
  pr-review-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-reviews-reminder-action@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: 'https://otagopoly.webhook.office.com/webhookb2/dff2c92e-097c-4d4c-a67d-1400199ddcbb@450e6824-88ab-4ad2-914d-b0f385da600c/IncomingWebhook/4d4eecb384a24dcbbcef0665559274f2/83ac2e7b-3d06-4f89-9775-232127186976'
        provider: 'msteams'
        channel: '#Important Updates'
        github-provider-map: '' 