name: Auto Assign Reviewer
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewer:
    name: Add Reviewer
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          configuration-path: ".github/auto_assign.yml"
